### ISSUE TITLE
Do you have hpack for nginx 1.14.1?

### ISSUE THREAD

**Issue by kevin25** [hakasenyang/openssl-patch#11]
Is it available to patch nginx 1.14.1 ?

**Comment by hakasenyang** [comment]
Perhaps you should use Cloudflare's patches.

I made a patch file based on the latest version and did not check that it works properly in the previous version.

**Comment by kevin25** [comment]
Thank you. 1.14.1 is the latest version.

**Comment by hakasenyang** [comment]
Sorry. Support "Mainline version".
Not support "Latest version".
