### ISSUE TITLE
openssl-1.1.1c-prioritize_chacha_draft.patch conflict with openssl-equal-1.1.1b_ciphers.patch

### ISSUE THREAD

**Issue by akw28888** [hakasenyang/openssl-patch#24]
Hi,

I am using these 2 patches with OpenSSL 1.1.1c, it seems these two patches have conflicts on ssl/s3_lib.c file

**Comment by hakasenyang** [comment]
Hello.

"openssl-1.1.1c-prioritize_chacha_draft.patch" can not be used with the "openssl-equal-1.1.1b_ciphers.patch" patch.

Please check my commit at the link below.

https://github.com/hakasenyang/openssl-patch/blob/master/openssl-equal-1.1.1b.patch#L169
https://github.com/hakasenyang/openssl-patch/blob/master/openssl-1.1.1c-prioritize_chacha_draft.patch#L7

The Equal Preference patch is a patch that sets the priority of the Cipher equal to [Ciphers|Ciphers2]:ETC...

The "openssl-1.1.1c-prioritize_chacha_draft.patch" patch is only used if you do not want to apply the Equal Preference but want to apply it to "CHACHA20-OLD".

Sorry. English is not going to be smooth, but I hope you understand.

**Comment by akw28888** [comment]
OK, I got it.
Thanks for your answer.
