### ISSUE TITLE
Fix OpenSSL 3.0 Patch for master branch

### ISSUE THREAD

**Issue by railjty** [hakasenyang/openssl-patch#35]
Now it has too many mistakes

**Comment by hakasenyang** [comment]
Yes, that is correct. I didn't care. Please check the committed content.
https://github.com/hakasenyang/openssl-patch/commit/3495b704123bd2ea8f6c8e19673ee53972ea74e8

**Comment by railjty** [comment]
Thank you very much! I spent a whole night and fixed it myself.
