### ISSUE TITLE
openssl-3.0.0-dev-chacha_draft.patch patch failed

### ISSUE THREAD

**Issue by Fudoshiki** [hakasenyang/openssl-patch#36]
same as https://github.com/hakasenyang/openssl-patch/issues/29, on with current openssl master

**Comment by hakasenyang** [comment]
Yes, current 3.0.0 version has a lot of API changes. If possible, it is recommended that you use the 1.1.1 chacha draft.
I'm looking for information about the changed API but haven't figured it out yet.
You can use it by reverting the following patch.

- https://github.com/openssl/openssl/commit/c8f6c28a938fc887ee3d2337f09db453e7fb0369
- https://github.com/openssl/openssl/commit/620c97b671a9c7bc31ca36a24b2242aa1aa80022#diff-97a3239e0939cd2a1cbc669d027852f1

In my opinion, modification of that file is probably necessary.
- providers/implementations/ciphers/cipher_chacha20_poly1305.c
