### ISSUE TITLE
openssl-1.1.1h-chacha_draft patch fails

### ISSUE THREAD

**Issue by morazow** [hakasenyang/openssl-patch#44]
Hello,

Thanks for the patches!

The `openssl-1.1.1h-chacha_draft` patch fails when applying to the OpenSSL version `1.1.1h`.

```sh
wget https://www.openssl.org/source/openssl-1.1.1h.tar.gz
tar -xf openssl-1.1.1h.tar.gz
cd openssl-1.1.1h/

wget https://raw.githubusercontent.com/hakasenyang/openssl-patch/master/openssl-1.1.1h-chacha_draft.patch

$ patch --dry-run -p1 < openssl-1.1.1h-chacha_draft.patch 
checking file crypto/evp/c_allc.c
checking file crypto/evp/e_chacha20_poly1305.c
checking file crypto/objects/obj_dat.h
checking file crypto/objects/obj_mac.num
checking file crypto/objects/objects.txt
checking file include/openssl/evp.h
checking file include/openssl/obj_mac.h
checking file include/openssl/ssl.h
checking file include/openssl/tls1.h
checking file ssl/s3_lib.c
checking file ssl/ssl_ciph.c
checking file ssl/ssl_local.h
checking file util/libcrypto.num
Hunk #1 FAILED at 4590.
1 out of 1 hunk FAILED
```

**Comment by EverybodyGetsHurt** [comment]
@morazow If you are still looking for a patch.

Here is a patch for OpenSSL-1.1.1u: https://github.com/EverybodyGetsHurt/OpenSSL-1.1.1u_chacha20-poly1305_draft/blob/main/OpenSSL-1.1.1u_chacha20-poly1305_draft.patch

**Comment by morazow** [comment]
Hello @EverybodyGetsHurt,

Thanks for the update and reminder!

I have recently moved to the 3.x version of OpenSSL (https://github.com/morazow/docker-nginx/) for Nginx image. 

We can close this issue for now.

**Comment by EverybodyGetsHurt** [comment]
@morazow 
Here is my patch for 3.2.0-dev, have fun.

https://github.com/EverybodyGetsHurt/OpenSSL-3.2.0-dev-OpenSSL-1.1.1u-chacha20-poly1305_draft/blob/master/OpenSSL-3.2.0-dev_chacha20-poly1305_draft.patch
