### ISSUE TITLE
[Request] Make the strict_sni_header-only patch for the Nginx 1.19.4 and above

### ISSUE THREAD

**Issue by KazamaSion** [hakasenyang/openssl-patch#45]
~Since Nginx 1.19.4 is released, the "strict-sni" patch is no longer needs to be used due to the feature [ssl_reject_handshake](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake).~   

~This issue is only for telling my huge thanks to you for your repo advanced my server's security. I will close the issue later.~  

Update: Nginx 1.19.4 does not implement the feature of `strict_sni_header`.   
Since Nginx already make the feature which works same as `strict_sni`, I hope the maintainer can make the `strict_sni_header`-only patch for the Nginx 1.19.4 and above.

**Comment by lzlrd** [comment]
> Since Nginx 1.19.4 is released, the "strict-sni" patch is no longer needs to be used due to the feature [ssl_reject_handshake](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake).
> 
> This issue is only for telling my huge thanks to you for your repo advanced my server's security. I will close the issue later.

Correct me if I'm wrong but `ssl_reject_handshake` seems to reject the handshake slightly different to how `strict_sni` and `strict_sni_header` does.

**Comment by KazamaSion** [comment]
> > Since Nginx 1.19.4 is released, the "strict-sni" patch is no longer needs to be used due to the feature [ssl_reject_handshake](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake).
> > This issue is only for telling my huge thanks to you for your repo advanced my server's security. I will close the issue later.
> 
> Correct me if I'm wrong but `ssl_reject_handshake` seems to reject the handshake slightly different to how `strict_sni` and `strict_sni_header` does.

~I am assuming that you are talking about the user can identify the difference between using `ssl_reject_handshake` and `strict-sni`. If so, I checked the returns, entirely same:~  
```
curl -k -v https://127.0.0.1
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, unrecognized name (624):
* error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
``` 

Their intentions are also familiar. For the `ssl_reject_handshake`, the [caption](http://hg.nginx.org/nginx/rev/59e1c73fe02b) is:   
> In some cases it might be needed to reject SSL handshake based on SNI server name provided, for example, to make sure an invalid certificate is not returned to clients... With this change, the ssl_reject_handshake directive is introduced, which instructs nginx to reject SSL handshakes with an "unrecognized_name" alert in a particular server block.

~If there's something has to be different, that should be the situation if the user wants to turn `strict_sni` on but turn `strict_sni_header` off.~  
~However, I do not think this should be discussed because it is meanless if only turn `strict_sni` on, if the user wants to prevent leaking SNI info from some scans like censys.~  

~If you find any difference without the situation above, tell me.~   

After commenting that, I re-checked the return. Actually, you are right. I did not check strictly after this feature released. There's something different:  

Nginx 1.19.4 with ssl_reject_handshake:
```
telnet 127.0.0.1 443
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
HTTP/1.1 400 Bad Request
Date: Tue, 03 Nov 2020 21:18:37 GMT
Content-Type: text/html
Content-Length: 122
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>
Connection closed by foreign host.
```

Nginx 1.19.3 with strict-sni patch:
```
telnet 127.0.0.1 443                                                                                                                                                          1 ↵
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```
  
My bad. Nginx 1.19.4 doesn't implement the `strict_sni_header` feature. And currently, `strict-sni` patch does not support Nginx 1.19.4 due to the feature of `ssl_reject_handshake`.   
  
So, may @hakasenyang intend to do the `strict_sni_header`-only patch for Nginx 1.19.4 and above?  
  
P.S. Since Nginx already makes the feature which works equally as `strict_sni`, I do not think adding `strict_sni` is necessary for Nginx 1.19.4 and above. And maybe, to follow how `ssl_reject_handshake` works, make `strict_sni_header` works in the `server` context shall be integrant. (If the maintainer intends to do so far, why not also rename `strict_sni_header` into `ssl_reject_invalid_header` and someday Nginx may merge this patch directly?)

**Comment by lzlrd** [comment]
I might give myself the task of extending ssl_reject_handshake if I can fit in some time, it seems fun.

**Comment by lzlrd** [comment]
@KazamaSion, could you give this a try https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc?

**Comment by KazamaSion** [comment]
> @KazamaSion, could you give this a try [ZestProjects/nginx@580a729](https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc)?

@lazerl0rd It seems like you modified the Nginx before, which cause the failure to apply your patch.  
So I remake the patch based on your commit. Check it here:  
https://gitlab.com/KazamaSion/nginx/-/commit/d9a3548bf211bc668c719a4f2943a8d21f961b52  
  
```
patching file src/http/modules/ngx_http_ssl_module.c
Hunk #1 FAILED at 301.
Hunk #2 succeeded at 622 (offset -44 lines).
Hunk #3 succeeded at 670 (offset -49 lines).
1 out of 3 hunks FAILED -- saving rejects to file src/http/modules/ngx_http_ssl_module.c.rej
patching file src/http/modules/ngx_http_ssl_module.h
patching file src/http/ngx_http_request.c
Hunk #1 succeeded at 1053 (offset -97 lines).
Hunk #2 succeeded at 1179 (offset -97 lines).
Hunk #3 succeeded at 1947 (offset -97 lines).
Hunk #4 succeeded at 1964 (offset -97 lines).
```  
The comparison of the `Hunk #1`'s nearby codes:  
![](https://i.loli.net/2020/11/05/H1LGFzgjx4okDri.png)  

Maybe I do the patch wrongly. It does not fix the problem:  
```
telnet 127.0.0.1 443
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
HTTP/1.1 400 Bad Request
Date: Wed, 04 Nov 2020 20:01:11 GMT
Content-Type: text/html
Content-Length: 122
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
</body>
</html>
Connection closed by foreign host.
```


Configuration: 
```
server {
    listen       80 default_server;
    server_name  localhost;
    listen       443 ssl http2 default_server;
    ssl_reject_handshake on;  
    ssl_reject_handshake_quietly on;
    location / {
        return 444;
    }
}
```

**Comment by lzlrd** [comment]
> > @KazamaSion, could you give this a try [ZestProjects/nginx@580a729](https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc)?
> 
> Maybe I do the patch wrongly. It does not fix the problem:


You're adjustment to my patch seems to be good, it seems my patch was at fault. Hopefully this one should work (it's also much smaller and simpler), https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d.

EDIT: I can confirm the new patch works.

**Comment by KazamaSion** [comment]
> > > @KazamaSion, could you give this a try [ZestProjects/nginx@580a729](https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc)?
> > 
> > 
> > Maybe I do the patch wrongly. It does not fix the problem:
> 
> You're adjustment to my patch seems to be good, it seems my patch was at fault. Hopefully this one should work (it's also much smaller and simpler), [ZestProjects/nginx@5ff3e15](https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d).
> 
> EDIT: I can confirm my new patch works!

@lazerl0rd Here's what happened.  
If using your patch for strict-sni-header only, like `curl https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc.diff | patch -p1 `, the result does not change.

If I clone your [ZestProjects/nginx](https://github.com/ZestProjects/nginx.git) then build the binary directly without specifying the OpenSSL version I want to use (means `--with-openssl` is not allowed), it works (also for the previous commit).  

As I mentioned before, you already modified the Nginx by yourself. If this is the patch for the public, you should consider rebasing your repo on the **OFFICIAL NGINX REPO** and then making the patch. (I've seen a lot of patches applied in your repo. I cannot figure out which of them cause the failure if only applying the `ssl_reject_handshake_quietly` patch.) I mean, you can't publish a patch needs users to apply other bunches of patches first, including http_v3, hpack, etc., to make sure it works. 

You did a great job, but it is the patch for the public use. That is the case.

**Comment by lzlrd** [comment]
> As I mentioned before, you already modified the Nginx by yourself. If this is the patch for the public, you should consider rebasing your repo on the **OFFICIAL NGINX REPO** and then making the patch. (I've seen a lot of patches applied in your repo. I cannot figure out which of them cause the failure if only applying the `ssl_reject_handshake_quietly` patch.) I mean, you can't publish a patch needs users to apply other bunches of patches first, including http_v3, hpack, etc., to make sure it works.

**You're using the wrong patch.**

The commit https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc is the OLDER patch, which I've stated above that it doesn't work. 

The NEW patch is commit https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d, which applies cleanly onto mainline NGINX. Remove all my previous commits from your tree, then test this:

`curl https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d.diff | patch -p1`

**Comment by KazamaSion** [comment]
> > As I mentioned before, you already modified the Nginx by yourself. If this is the patch for the public, you should consider rebasing your repo on the **OFFICIAL NGINX REPO** and then making the patch. (I've seen a lot of patches applied in your repo. I cannot figure out which of them cause the failure if only applying the `ssl_reject_handshake_quietly` patch.) I mean, you can't publish a patch needs users to apply other bunches of patches first, including http_v3, hpack, etc., to make sure it works.
> 
> **You're using the wrong patch.**
> 
> The commit [ZestProjects/nginx@580a729](https://github.com/ZestProjects/nginx/commit/580a7291196ea0cadf13ef145c67ddca94ac68fc) is the OLDER patch, which I've stated above that it doesn't work.
> 
> The NEW patch is commit [ZestProjects/nginx@5ff3e15](https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d), which applies cleanly onto mainline NGINX. Remove all my previous commits from your tree, then test this:
> 
> `curl https://github.com/ZestProjects/nginx/commit/5ff3e15ab1d12f6503dbef1bc596faa1f7dca14d.diff | patch -p1`


I revise my word. It also doesn't work without using your whole repo. I actually use your lastest patch and try to fix the patch failure in [GitLab:KazamaSion/nginx@0f6e2e](https://gitlab.com/KazamaSion/nginx/-/commit/0f6e2e1bd337c21d47c18f9d8b1200e7b80bd794). The only reason I write the old patch hash in the comment is because I used it for the first try. I did not expect this will make confusion.   
Meantime, I mentioned that the old patch works too, referred to the sentence "it works (also for the previous commit)".

**Comment by lzlrd** [comment]
> I revise my word. It also doesn't work without using your whole repo. I actually use your lastest patch and try to fix the patch failure in [GitLab:KazamaSion/nginx@0f6e2e](https://gitlab.com/KazamaSion/nginx/-/commit/0f6e2e1bd337c21d47c18f9d8b1200e7b80bd794). The only reason I write the old patch hash in the comment is because I used it for the first try. I did not expect this will make confusion.
> Meantime, I mentioned that the old patch actually works, referred to the sentence "it works (also for the previous commit)".

_Are you sure you're not forgetting to restart NGINX or something?_

**The older patch shouldn't work** (or at least, it won't work in the few scenarios I tested), the logic of the code was wrong. **The new patch doesn't rely on any other patches my fork contains - at all.** The only patch my new patch relies on is the patch in official NGINX 1.19.4 for `ssl_reject_handshake`.

If I were to explain what the patch does, it uses adds an option to the native NGINX SSL configuration (`ssl_reject_handshake_quietly`) which when set to `on` along with `ssl_reject_handshake` will terminate the current request for any rejected handshakes. It's literally some pointer manipulation and a call to `ngx_http_terminate_request()` which none of my patches have modified.

I'm about to go to sleep now but I can give mainline NGINX a test with my patch in the morning.

**Comment by KazamaSion** [comment]
> > I revise my word. It also doesn't work without using your whole repo. I actually use your lastest patch and try to fix the patch failure in [GitLab:KazamaSion/nginx@0f6e2e](https://gitlab.com/KazamaSion/nginx/-/commit/0f6e2e1bd337c21d47c18f9d8b1200e7b80bd794). The only reason I write the old patch hash in the comment is because I used it for the first try. I did not expect this will make confusion.
> > Meantime, I mentioned that the old patch actually works, referred to the sentence "it works (also for the previous commit)".
> 
> _Are you sure you're not forgetting to restart NGINX or something?_
> 
> **The older patch shouldn't work** (or at least, it won't work in the few scenarios I tested), the logic of the code was wrong. **The new patch doesn't rely on any other patches my fork contains - at all.** The only patch my new patch relies on is the patch in official NGINX 1.19.4 for `ssl_reject_handshake`.
> 
> If I were to explain what the patch does, it uses adds an option to the native NGINX SSL configuration (`ssl_reject_handshake_quietly`) which when set to `on` along with `ssl_reject_handshake` will terminate the current request for any rejected handshakes. It's literally some pointer manipulation and a call to `ngx_http_terminate_request()` which none of my patches have modified.
> 
> I'm about to go to sleep now; I can give mainline NGINX a test with my patch in the morning but I'm pretty certain it'll work fine.

FYI, I re-create a new virtual machine and do the patch on the latest Nginx 1.19.4 with OpenSSL 1.1.1h. This is a brand new environment so there is no restart issue.

Chill. We are not in hurry. There is no ice on the road.  

I've re-test it with the following things:

Configuration:
```
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen       80;
        server_name  localhost;
        listen       443;
        ssl_reject_handshake on;
        ssl_reject_handshake_quietly on;
        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
```

Result:
curl:
```
curl -k -v https://127.0.0.1
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

telnet: (Use Ctrl+D to terminate the process)
```
telnet 127.0.0.1 443
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
HTTP/1.1 400 Bad Request
Server: nginx/1.19.4
Date: Wed, 04 Nov 2020 23:15:53 GMT
Content-Type: text/html
Content-Length: 157
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.19.4</center>
</body>
</html>
Connection closed by foreign host.
```


Commands:
```
wget http://nginx.org/download/nginx-1.19.4.tar.gz
tar zxf nginx-*.tar.gz && rm nginx-*.tar.gz
cd nginx-1*/ 
curl https://gitlab.com/KazamaSion/nginx/-/commit/0f6e2e1bd337c21d47c18f9d8b1200e7b80bd794.diff | patch -p1  

./configure --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-rpath,/usr/local/lib,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_realip_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_flv_module --with-http_random_index_module --with-http_secure_link_module --with-http_sub_module


make && make install 
```

**Comment by KazamaSion** [comment]
I don't know why you delete the reply when I have time to test your latest patch. 
To contribute it to the official, you can email ***@***.***` while following the guide [here](http://nginx.org/en/docs/contributing_changes.html) instead of sending others to contribute it for you.
