### ISSUE TITLE
an OpenSSL way to enable Chacha20 Priority feature

### ISSUE THREAD

**Issue by S8Cloud** [hakasenyang/openssl-patch#5]
OpenSSL has its own implementation to prioritize Chacha20 when client does.

https://github.com/openssl/openssl/blob/ef2dfc9902e015de91f015177bdf235c9000839e/include/openssl/ssl.h#L355

It is easy to enable this feature by default and it does the same work of BoringSSL's Equal Preference 

```
diff --git a/ssl/s3_lib.c b/ssl/s3_lib.c
index 7713f76..e8ad162 100644
--- a/ssl/s3_lib.c
+++ b/ssl/s3_lib.c
@@ -4159,7 +4159,7 @@ const SSL_CIPHER *ssl3_choose_cipher(SSL *s, STACK_OF(SSL_CIPHER) *clnt,
         /* If ChaCha20 is at the top of the client preference list,
            and there are ChaCha20 ciphers in the server list, then
            temporarily prioritize all ChaCha20 ciphers in the servers list. */
-        if (s->options & SSL_OP_PRIORITIZE_CHACHA && sk_SSL_CIPHER_num(clnt) > 0) {
+        if (sk_SSL_CIPHER_num(clnt) > 0) {
             c = sk_SSL_CIPHER_value(clnt, 0);
             if (c->algorithm_enc == SSL_CHACHA20POLY1305) {
                 /* ChaCha20 is client preferred, check server... */
```

**Comment by hakasenyang** [comment]
Yes, that is correct.

However, you can use any of the other methods for prioritization, such as AES128 and AES256.

Ex)
``[EECDH+AES128+AESGCM|EECDH+AES256+AESGCM]:EECDH+CHACHA20``
``[EECDH+CHACHA20|EECDH+AES256|EECDH+AES128]``
etc.

**Comment by hakasenyang** [comment]
You can set CHACHA20 priority in nginx without patching OpenSSL.

Please patch and build it as follows.

```diff
diff --git a/src/event/ngx_event_openssl.c b/src/event/ngx_event_openssl.c
index 75129134..cb3cc023 100644
--- a/src/event/ngx_event_openssl.c
+++ b/src/event/ngx_event_openssl.c
@@ -358,6 +358,10 @@ ngx_ssl_create(ngx_ssl_t *ssl, ngx_uint_t protocols, void *data)
     SSL_CTX_set_options(ssl->ctx, SSL_OP_NO_ANTI_REPLAY);
 #endif

+#ifdef SSL_OP_PRIORITIZE_CHACHA
+    SSL_CTX_set_options(ssl->ctx, SSL_OP_PRIORITIZE_CHACHA);
+#endif
+
 #ifdef SSL_MODE_RELEASE_BUFFERS
     SSL_CTX_set_mode(ssl->ctx, SSL_MODE_RELEASE_BUFFERS);
 #endif
```

**Comment by S8Cloud** [comment]
Yes this feature was added half a year ago by openssl team, but nginx team thought it was more like a hack than a feature and refused to add an option to enable it.

**Comment by S8Cloud** [comment]
What's the meaning of setting  `[EECDH+AES128+AESGCM|EECDH+AES256+AESGCM]:EECDH+CHACHA20`?
It seems the same as `EECDH+AESGCM:EECDH+CHACHA20` without using equal preference.

**Comment by hakasenyang** [comment]
Depending on the priority of the browser, either AES128 or AES256 is selected.
If AES128 and AES256 are not supported, CHACHA20 is selected.
