### ISSUE TITLE
about "add TLS1_3 to ngx_conf_merge_bitmask_value".

### ISSUE THREAD

**Issue by NewBugger** [hakasenyang/openssl-patch#6]
[here](https://github.com/hakasenyang/openssl-patch/issues/1#issuecomment-414051883), i saw a patch like this :
```c
ngx_conf_merge_bitmask_value(conf->protocols, prev->protocols,
                         (NGX_CONF_BITMASK_SET|NGX_SSL_TLSv1
                          |NGX_SSL_TLSv1_1|NGX_SSL_TLSv1_2|NGX_SSL_TLSv1_3));
```

i made a [commit](https://github.com/Minaminx/Core/commit/e983ac7e078158ccfdb3757da217ccbf58308b4a) and it worked now.

the matter is, what's the situation to apply it and what's the concrete purpose ? whatever either OpenSSL or BoringSSL supports TLSv1.3 for Nginx now.

**Comment by hakasenyang** [comment]
Yes. BoringSSL or OpenSSL is already support TLSv1.3.

That source means the following defaults:
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

The default ssl_protocols for nginx are only up to TLSv1.2 and have been modified.

**Comment by NewBugger** [comment]
soga. 

>> That source means the default ssl_protocols for nginx.
