### ISSUE TITLE
Question: how to just enable one feature of the openssl patch

### ISSUE THREAD

**Issue by S8Cloud** [hakasenyang/openssl-patch#8]
The openssl-equal-1.1.1.patch is great but it is a complex combination of various functions.
How can I just enable previous TLS 1.3 draft feature?

**Comment by hakasenyang** [comment]
I will upload a patch that will apply only those functions within today. :)

**Comment by hakasenyang** [comment]
Updated!

View : https://github.com/hakasenyang/openssl-patch/blob/d34f47744d59f4cd23725b915dd451380d56b4e9/openssl-1.1.1-tls13_draft.patch

**Comment by hakasenyang** [comment]
@centminmod Hello.
https://github.com/hakasenyang/nginx-build/issues/3#issuecomment-430477300
It fails because SSLLabs only support TLS 1.3 final tests.

**Comment by centminmod** [comment]
I suggested as much... cheers !
